### ISSUE TITLE
Add (Post) Project

### ISSUE THREAD

**Issue by ValAring** [ValAring/VAring-CapstoneProject#2]
**As a User** 
**I need** ###
**to be able to** ###

## Acceptance Criteria

- [x] Create a POST "/api" endpoint to post projects to the backend.

## Tasks

(for developers team)

- [x] Create a Model with "Id, author, description"
- [x] Create a "Add projects" component in the UI.
- [x] Implement a POST request to post projects to the backend.
- [x] Update the frontend to display the created project.
- [x] Implement Unit and Integration Test.
- [x] add some styling
