### ISSUE TITLE
GetAllProjects

### ISSUE THREAD

**Issue by ValAring** [ValAring/VAring-CapstoneProject#3]
**As a User** 
**I need** to view a list of all my projects
**to be able to** have an overview of all my projects.

## Description
Implement a feature that allows users to retrieve and view a list of all their projects from the backend.

## Acceptance Criteria

- [x] Create a GET "/api" endpoint to fetch all books from the backend.
- [x] Display the list of all projects on the starting page of the frontend.

## Tasks

(for developers team)

- [x] Create a Model with "Id, author, description"
- [x] Create a "View All projects" component in the UI.
- [x] Implement a GET request to retrieve all projects from the backend.
- [x] Update the frontend to display the list ofprojects.
- [x] Implement Unit and Integration Test.
- [x] add some styling
